/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/global/AppLogo.vue')['default']
    ElButton: typeof import("element-plus/es")["ElButton"]
    Logo: typeof import("./src/components/global/Logo.vue")["default"]
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
